mewes_k_web_redirector:
    resource: "@MewesKWebRedirectorBundle/Controller/"
    type:     annotation
    prefix:   /

mewes_k_web_redirector_yml:
    resource: "@MewesKWebRedirectorBundle/Resources/config/routing.yml"