security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /admin

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
