services:
    mewesk.twig.web_redirector_extension:
        class: MewesK\WebRedirectorBundle\Twig\WebRedirectorExtension
        tags:
            - { name: twig.extension }

    mewesk.type.mewesk_webredirectorbundle_redirect:
         class: MewesK\WebRedirectorBundle\Form\RedirectType
         tags:
         - { name: form.type, alias: mewesk_webredirectorbundle_redirect }

    mewesk.type.mewesk_webredirectorbundle_test:
         class: MewesK\WebRedirectorBundle\Form\TestType
         tags:
         - { name: form.type, alias: mewesk_webredirectorbundle_test }